/**
 * Node factory — creates a `BlueprintNode` for a given atom type with
 * sensible authoring defaults that produce a VALID contract on drop.
 *
 * Why defaults matter:
 * Blueprint's zod schemas mandate `name.min(1)` on every form input
 * (field / select / checkbox / … ) and `options.min(1)` on enum-style
 * atoms (select / radio). Dropping a bare atom with `name: ''` used to
 * create an instantly-invalid contract. We now seed each atom with
 * short, unique-enough defaults so the designer can drop-and-tweak
 * instead of drop-and-fix-errors.
 *
 * The Inspector's schema-driven editor is the primary UI for changing
 * these values; the defaults here are conservative starting points.
 */
import type { AtomType, BlueprintNode } from './types';
import { ATOMS_REQUIRING_ID } from '@dashforge/blueprint-core';

/**
 * ID generator — short, collision-safe within a single editor session.
 * We don't need cryptographic uniqueness; a random base36 tag is
 * enough for palette-scale usage and ships small in the exported JSON.
 */
export function uid(): string {
  return 'n_' + Math.random().toString(36).slice(2, 10);
}

/**
 * Friendly default for the PUBLIC `nodeId` — `form-a3k9`, `select-9fx2`.
 * Every node gets one on drop (nodeId is mandatory in the Builder); the
 * designer renames it freely. Self-describing so a fresh contract reads
 * sensibly before anyone touches it — unlike the opaque `_uid` handle.
 */
function semanticId(type: AtomType): string {
  return `${type}-${Math.random().toString(36).slice(2, 6)}`;
}

/**
 * 4-char random tag we append to auto-generated names so two dropped
 * atoms of the same type never end up with the same `props.name` and
 * shadow each other in Blueprint's form state.
 */
function randTag(): string {
  return Math.random().toString(36).slice(2, 6);
}

/** Default single option for select / radio — one is the minimum. */
const oneOption = () => [{ value: 'option-1', label: 'Option 1' }];

/**
 * Build the default `props` for a given atom type. Keeping this a
 * function (not a static record) lets us randomise names on every
 * drop, so the designer never gets accidentally-collided form fields.
 */
function defaultPropsFor(type: AtomType): Record<string, unknown> {
  const tag = randTag();
  switch (type) {
    // ─── Container / layout atoms ────────────────────────────────
    // `form` props are `z.object({}).strict()` — the form's identity
    // lives on the ENVELOPE id (`node.id`), not on `props.id`. The
    // node.id 'n_XXX' generated by `createNode` satisfies the
    // `ATOMS_REQUIRING_ID` validator check; the user renames it to
    // something meaningful (e.g. 'checkout') via the Inspector.
    case 'form':      return {};
    // F-09 sweep: every default below must round-trip through the
    // matching zod schema in `blueprint-core/atoms.ts`. Previously ~7
    // atoms shipped invalid keys on drop (see BUILDER-DOGFOOD-REPORT
    // §F-09).
    case 'stack':     return { direction: 'column', spacing: 'md' };
    case 'grid':      return { cols: 2 };
    case 'section':   return { spacing: 'md' };
    case 'card':      return {};
    case 'container': return {};
    case 'box':       return {};

    // ─── Form inputs (all require `name.min(1)`) ─────────────────
    // F-05 revert: `label` is a `translatableStringSchema` = union of
    // non-empty string or `$t` ref — empty string fails validation
    // immediately, which is worse than the placeholder problem F-05
    // tried to solve. Restore friendly capitalised default; ship the
    // "warn when label is still the placeholder" nudge as F-08 later.
    case 'field':        return { name: 'field_' + tag, label: 'Field' };
    case 'textarea':     return { name: 'textarea_' + tag, label: 'Textarea' };
    case 'number':       return { name: 'number_' + tag, label: 'Number' };
    case 'select':       return { name: 'select_' + tag, label: 'Select', options: oneOption() };
    case 'autocomplete': return { name: 'autocomplete_' + tag, label: 'Autocomplete', options: oneOption() };
    case 'checkbox':     return { name: 'checkbox_' + tag, label: 'Checkbox' };
    case 'switch':       return { name: 'switch_' + tag, label: 'Switch' };
    case 'radio':        return { name: 'radio_' + tag, label: 'Radio', options: oneOption() };
    case 'date':         return { name: 'date_' + tag, label: 'Date' };
    case 'time':         return { name: 'time_' + tag, label: 'Time' };
    case 'dateTime':     return { name: 'dateTime_' + tag, label: 'Date & time' };
    case 'dateRange':    return { name: 'dateRange_' + tag, label: 'Date range' };
    case 'otp':          return { name: 'otp_' + tag, label: 'OTP', length: 6 };

    // ─── Actions ─────────────────────────────────────────────────
    case 'submit':     return { label: 'Submit' };
    case 'button':     return { label: 'Button' };
    // `icon` must resolve inside the consumer's `<DashBlueprint icons>`
    // registry at runtime. `save` is the canonical playground/demo id
    // (see `src/playground/iconSources.tsx`) — the Builder user still
    // overrides it via the Icon Picker in the Inspector.
    case 'iconButton': return { icon: 'save', ariaLabel: 'Action' };

    // ─── Content ─────────────────────────────────────────────────
    // Heading/text render their body through `children` (string OR
    // InlineNode[]) — not `text`. Level is required on heading.
    case 'heading': return { level: 2, children: 'Heading' };
    case 'text':    return { children: 'Body text' };
    case 'alert':   return { title: 'Alert', severity: 'info' };
    case 'divider': return {};

    // ─── Navigation ──────────────────────────────────────────────
    // tabs/accordion items key on `value` (not `id`). Accordion needs
    // a `type` discriminator picked before render; `single` is the
    // more common shape.
    case 'tabs':        return { items: [{ value: 'tab-1', label: 'Tab 1' }] };
    case 'accordion':   return { type: 'single', items: [{ value: 'item-1', header: 'Section' }] };
    case 'breadcrumbs': return { items: [{ id: 'home', label: 'Home' }] };
    case 'pagination':  return { totalCount: 10 };

    // ─── Display ─────────────────────────────────────────────────
    case 'badge':    return { content: '1' };
    case 'chip':     return { label: 'Chip' };
    // avatarProps has no `alt` — the accessible name derives from
    // `name` (initials fallback) or the wrapping component.
    case 'avatar':   return {};
    case 'tooltip':  return { content: 'Tooltip text', icon: 'info-circle' };
    case 'calendar': return {};

    // Media
    case 'image':
      return {
        src: 'https://picsum.photos/seed/blueprint/800/450',
        alt: 'Image',
        aspectRatio: '16 / 9',
        rounded: 'md',
      };
    case 'video':
      return {
        src: 'https://mdn.github.io/shared-assets/videos/flower.mp4',
        poster: 'https://picsum.photos/seed/blueprint-video/800/450',
        aspectRatio: '16 / 9',
        rounded: 'md',
        controls: true,
      };

    default: return {};
  }
}

/**
 * Create a new node of the given type. Children start empty even for
 * container atoms — the user drops into them explicitly.
 */
export function createNode(type: AtomType): BlueprintNode {
  return {
    // Immutable internal handle (Builder-only, stripped on export) + a
    // friendly public nodeId every node carries by default.
    _uid: uid(),
    nodeId: semanticId(type),
    type,
    props: defaultPropsFor(type),
    children: [],
  };
}
